steps:
  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npm run build
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-node-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/my-node-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
