steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'my-app', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-v', '/workspace:/app', '-w', '/app', 'my-app', 'pip', 'install', '-r', 'requirements.txt']

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-v', '/workspace:/app', '-w', '/app', 'my-app', 'python', 'app.py']

